### PR TITLE
coordinates: show lat/lng on request

### PR DESCRIPTION
**Pull request by msslovi0**
Cleaned things up.

Adds a new button that shows lat/lng in a javascript prompt as on the old map.

Also addresses a bug that the sidebar button doesn't transform.

### CODE REVIEW

**Comment by stebifan** [comment]
lat/lng button: I've waited for that! It's a verry important feature!

**Comment by tcatm** [comment]
I'm wondering whether it might be a better approach to create a marker that the use can move to place a node. That we it might be easier to place nodes the the correct position on touch devices.

**Comment by rekatab** [comment]
cool feature. I missed that a lot! ;)

**Comment by tcatm** [comment]
I think the icon is misleading and conflicts with the "locate user" icon. Also it should be an alert, not a prompt as the user is not supposed to edit the value.

**Comment by msslovi0** [comment]
I picked the one used currently as it is named locate. But yes, it's pretty close to the other icon. Maybe the marker icon would be a better choice.

I thought about that prompt, too, because I wondered why it was a prompt on the old map in the first place. My best guess is that users are not aware that they can copy text from an alert while it's clear when the dialog is a prompt so I kept the prompt.

**Comment by flokli** [comment]
I'm fine with a prompt - Makes copying a lot easier. It would be overkill to add a modal dialog just to copy two values - especially given there is currently no framework in place that brings this feature.

**Comment by tcatm** [comment]
Can we drop the `-webkit-transform` commit? There are browsers available supporting `transform` for virtually all operating systems and it'll make this pull request simpler.

I've recommended (Flopp's Karte)[http://www.flopp.net/] to others looking for a way to get coordinates of new nodes and I've come to like the approach used there better (markers that can be moved, multiple markers). Maybe we can add a link (in "Über") to it? It might even be possible to export all existing nodes using GeoJSON. That way, we wouldn't have to duplicate features.

**Comment by msslovi0** [comment]
I dropped the --webkit-transform commit. However, we are dealing with ordinary people here that use the map. These are not willing to install another browser (or not even able to) but keep telling me that the arrow is not working as intended. 

In order to keep the CSS tidy but address this issue anyway, http://leaverou.github.io/prefixfree/ might be a solution.

**Comment by kokel** [comment]
:+1: for this feature!

**Comment by tcatm** [comment]
This is still using a misleading icon and it doesn't attempt to change the cursor so it's rather confusing for users.

**Comment by tcatm** [comment]
\f1ff (ion-location) may be more appropriate

**Comment by msslovi0** [comment]
Changed the icon to \f1ff

**Comment by tcatm** [comment]
Great. What do you think about changing the cursor to a cross-hair when the feature is enabled?

**Comment by msslovi0** [comment]
Is there a more elegant way to do this other than this?
```javascript
document.getElementsByClassName('map')[0].style.cursor = "crosshair"

**Comment by tcatm** [comment]
Add a CSS rule, e.g.:

    .map.place-marker { cursor: "crosshair" }

and toggle the class like this:

    el.classList.add("place-marker")
    el.classList.remove("place-marker")

**Comment by msslovi0** [comment]
Just saw that there have been quite some updates to the original repo and tried to update my local copy but it doesn't run. Will reopen when I find the time to look into this.

**Comment by msslovi0** [comment]
Did you change how event handlers work? I have a working copy on the latest codebase here:
http://wibros.aries.uberspace.de/freifunk/meshviewer/
But the click handler only fires on second click (tested in Safari, Chrome and Firefox). The same code on the old codebase fired on the first click.

**Comment by tcatm** [comment]
That's interesting. I didn't change anything related to event handlers.

**Pull request closed without merging**
