### PR TITLE
Show lost nodes in background of the other points in map view

### PR DESCRIPTION
**Pull request by stebifan**
See here: https://forum.freifunk.net/t/ffmap-backend-v1-und-meshviewer-v2/4123/174

### CODE REVIEW

**Comment by tcatm** [comment]
I wonder whether changing the ordering to (background to foreground) offline, online, lost, new would be more appropiate. Could you try that?

**Comment by stebifan** [comment]
In this case the lost nodes were on top of the online nodes. In a low zoom level the whole city will look offline.
The ordering offline, lost, online, net would be ok...

**Comment by tcatm** [comment]
That would be the point: Make it easy to notice nodes that have gone offline recently so people can urge the owners to fix them.

**Comment by stebifan** [comment]
In my workflow, i see lost nodes in the List on the left. For "normal" People the first impression of a Map with Red blinking dots is not so good.

**Comment by tcatm** [comment]
Meshviewer was never intended for "normal" people. It's a tool for network administrators and node owners to help build a more reliable network. A pretty map for "normal" people can be found at http://www.freifunk-karte.de/

**Comment by stebifan** [comment]
Not my point of view. But ok.
I just think, that the map should not be "red blinking" all time. 1 node is allways down in most times.

**Comment by rekatab** [comment]
an administrator should not rely on the colour of dots on the map because not every node is shown on the map. Here he only should look at "Verschwunde Knoten" in "Übersicht" because here all lost and offline Nodes are listet. 
And: if the map allways looks red, an administrator becomes unsensible for red dots.

To show red dots only to those who wants to see them (by zooming in) is the better way.

**Pull request closed without merging**
