### PR TITLE
added install instructions in README

### PR DESCRIPTION
**Pull request by rubo77**
Those instructions are needed to install. But still there is nothing happening when I call 

    grunt

How do you install this so it works?

### CODE REVIEW

**Comment by tcatm** [comment]
There's no need for sudo. You can install all packages locally (and run them using `node_modules/.bin/grunt`).

**Comment by rubo77** [comment]
the same if I run

    node_modules/.bin/grunt

just nothing happens.

    grunt --help 

doesn't show any output either

**Comment by tcatm** [comment]
Did you install grunt locally (npm install grunt-cli)?

**Comment by rubo77** [comment]
On Ubuntu there is no need of the often installed package `node`:

    sudo apt-get remove --purge node
    sudo ln -s /usr/bin/nodejs /usr/bin/node

**Comment by rubo77** [comment]
now grunt works, but some errors:

	Loading "connect.js" tasks...ERROR
	>> Error: Cannot find module 'ms'
	Loading "check-dependencies.js" tasks...ERROR
	>> Error: Cannot find module 'lodash._createwrapper'

	Running "eslint:sources" (eslint) task

	...

	Running "sass:dist" (sass) task
	Error: File to import not found or unreadable: _leaflet.
	       Load path: /var/www/freifunk/meshviewer
	        on line 3 of scss/main.scss
	  Use --trace for backtrace.
	Warning: Exited with error code 1 Use --force to continue.

**Comment by tcatm** [comment]
Did you run bower install (or node_modules/.bin/bower install)?

**Comment by rubo77** [comment]
I found out:

# Installing dependencies

	apt-get install nodejs

start with a clean `node_modules/` folder

	sudo rm -Rf node_modules/

install dependencies

    npm install bower
    npm install grunt-cli
    npm install sass

on Ubuntu there is no need of `node`:

    sudo apt-get remove --purge node
    sudo ln -s /usr/bin/nodejs /usr/bin/node
    
Be sure everything in `~/.npm/` belongs to you:

    sudo chown $USER:$USER -Rf ~/.npm/

Now start install:

    sudo npm install
    bower install
    grunt

**Comment by tcatm** [comment]
That's way more complicated than it needs to be.

Just make sure npm is installed, then run:

npm install bower
npm install grunt-cli
npm install
node_modules/.bin/bower install
node_modules/.bin/grunt

**Comment by rubo77** [comment]
It worked fine with just 

    bower install

and 

    grunt

can youo install npm without installing nodejs?

**Comment by tcatm** [comment]
npm depends on nodejs

**Comment by rubo77** [comment]
new request: https://github.com/tcatm/meshviewer/pull/2

**Pull request closed without merging**
