### PR TITLE
show router hardware in link info

### PR DESCRIPTION
**Pull request by plumpudding**

### CODE REVIEW

**Comment by tcatm** [comment]
What's the rationale behind this?

**Comment by plumpudding** [comment]
I like seeing the hardware when looking at a link. You don't have to accept this. I'll keep it in my fork otherwise.

**Comment by tcatm** [comment]
Could you take into account the case when dictGet returns null?

**Comment by plumpudding** [comment]
should be ok now

**Comment by tcatm** [comment]
Could you rebase/squash this into a single commit with a meaningful commit message (i.e. "those errors suck" doesn't help anyone).

**Comment by tcatm** [comment]
I'd also omit the if(!d.vpn). This information is present for VPN links, too.

**Comment by plumpudding** [comment]
done

**Pull request merged**
